plugins:
   - jekyll-paginate-v2
   - gh-pages

pagination:
  enabled: true
  # debug: true
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  # title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
